export const theme = {
  global: {
    globalBg:
      "linear-gradient(180deg, rgba(142, 84, 233, 0.52) 0%, #89D5FF 100%)",
    defaultBg: "#ffffff",
    defaultClr: "#C8A9F8",
    activeBg: "#C8A9F8",
    activeClr: "#ffffff",
    titleClr: "#ffffff",
    borderColor: "#b5b5b5",
    fontFamily1: "Roboto Slab",
    fontFamily2: "Roboto Mono",
    fontFamily3: "IBM Plex Mono",
  },
  counter: {
    btnClr: "#ffffff",
    primary: "#ffdab7",
    plus: "#7ccbff",
    minus: "#ff8b5d",
    fontSecondary: "'Poppins', sans-serif",
    fontPrimary: "'VT323', monospace",
    background: "#79bac2",
  },
  hackertyper: {
    background: "#000000",
    primary: "#00ff00",
    hover: "#009100",
    backgroundGranted: "#585858",
    denied: "#fd3131",
    backgroundDenied: "#5a0000",
    fontSecondary: "'Press Start 2P', cursive;",
    fontPrimary: "'IBM Plex Mono', monospace",
  },
  todo: {
    accent: "#ead7d7",
    base: "#f5f5f5",
    faded: "#e6e6e6",
    primary: "#7b7777",
    pale: "#f1ffff",
    h1Font: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    background: "#f5f5f5",
    white: "#FFFFFF",
  },

  tictactoe: {
    primary: "#ff8133",
    secondary: "#0b454d",
    box: "#ce903f",
    background: "#d1d1d1",
    primaryTextColor: "#ffffff",
    fontPrimary: '"Cabin Sketch", cursive',
    fontSecondary: "monospace",
  },

  memoryGame: {
    primary: "#33ff3d",
    flipped: "#2b6d6d",
    notFlipped: "#6d83ac",
    background: "#212746",
    primaryTextColor: "#bcb1ca",
    fontPrimary: "'Delius Swash Caps', cursive",
    fontSecondary: "monospace",
  },

  blog: {
    primary: "#ededed ",
    secondary: "#92929285",
    background: "#e4e4e4",
    primaryTextColor: "#00d1c0",
    secondaryTextColor: "#1a3a36",
    hoverTextColor: "#FFFFFF",
    fontPrimary: "'Roboto', sans-serif;",
    fontSecondary: "'Roboto', sans-serif;",
    errorColor: "#ff0800",
    iconSize: "2em",
  },
  redux: {
    black: "#000000",
    white: "#ffffff",
    grey: "#d8d8d8",
    orange: "#c7813f",
  },

  chuck: {
    scrollbarThumb: "#1c01014c",
    scrollbar: "#f5f5f5",
    scrollbarTrack: "#aaaaaa",
    scrollbarShadow: "inset 0 0 6px rgba(0, 0, 0, 0.3)",
    background: "#c9c9c9",
    primaryColor: "#240202",
    secondaryColor: "#85180a",
    toastBackground: "#ffffff",
    primaryFont: "'Special Elite', cursive",
    secondaryFont: "'Smokum', cursive",
  },
};
