export const theme = {
  global: {
    globalBg: "linear-gradient(180deg, #8e54e984 0%, #89D5FF 100%)",
    defaultBg: "#ffffff",
    defaultClr: "#C8A9F8",
    activeBg: "#C8A9F8",
    activeClr: "#ffffff",
    titleClr: "#ffffff",
    borderColor: "#b5b5b5",
    fontFamily1: "Roboto Slab",
    fontFamily2: "Roboto Mono",
    fontFamily3: "IBM Plex Mono",
  },
  counter: {
    btnClr: "#ffffff",
    nmbrClr: "#8e54e984",
    fontSecondary: "'Poppins', sans-serif",
    fontPrimary: "'VT323', monospace",
  },
  hackertyper: {
    background: "transparent",
    primary: "#8046df",
    secondary: "#89D5FF",
    popupBackground: "#8f8f8f",
    granted: "#9dff00",
    denied: "#ff0000",
    fontSecondary: "'Press Start 2P', cursive;",
    fontPrimary: "'IBM Plex Mono', monospace",
  },
  todo: {
    accent: "#ead7d7",
    base: "#f5f5f5",
    primary: "#8e54e984",
    secondary: "#89D5FF",
    white: "#FFFFFF",
    pale: "#f1ffff",
    h1Font: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    background: "transparent",
  },

  tictactoe: {
    primary: "#ffffff",
    secondary: "#0b454d",
    tertiary: "#ff8133",
    fontPrimary: "'Abel', sans-serif",
    fontSecondary: "monospace",
  },

  memoryGame: {
    primary: "#33ff3d",
    flipped: "#2b6d6d",
    notFlipped: "#6d83ac",
    background: "#212746",
    primaryTextColor: "#bcb1ca",
    fontPrimary: "'Delius Swash Caps', cursive",
    fontSecondary: "monospace",
  },

  blog: {
    primary: "#8e54e984 ",
    secondary: "#89D5FF",
    white: "#ffffff",
    primaryTextColor: "#00d1c0",
    secondaryTextColor: "#1a3a36",
    fontPrimary: "'Roboto', sans-serif;",
    fontSecondary: "'Roboto', sans-serif;",
    errorColor: "#ff0800",
  },
  redux: {
    black: "#8e54e984",
    white: "#ffffff",
    grey: "#d8d8d8",
    orange: "#89D5FF",
  },

  chuck: {
    scrollbarThumb: "#8e54e984",
    scrollbar: "#ffffff",
    scrollbarTrack: "#8e54e984",
    scrollbarShadow: "inset 0 0 6px #8e54e984",
    background: "#c9c9c9",
    primaryColor: "#8d54e9",
    secondaryColor: "#89D5FF",
    white: "#ffffff",
    primaryFont: "'Special Elite', cursive",
    secondaryFont: "'Smokum', cursive",
  },
};
